Source/AutoCarWebApp/autodrivetest/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^testreg/', include('testreg.urls')),
    url(r'^admin/', admin.site.urls),
]

Source/AutoCarWebApp/testreg/urls.py
from django.conf.urls import url

from . import views

app_name = 'testreg'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^newreg$', views.newreg, name='newreg'),
    url(r'^newapl$', views.newapl, name='newapl'),
    url(r'^listreg$', views.listreg, name='listreg'),
    url(r'^(?P<id>[0-9]+)/deletereg$', views.deletereg, name='deletereg'),
    url(r'^(?P<id>[0-9]+)/updatereg$', views.updatereg, name='updatereg'),
    url(r'^(?P<id>[0-9]+)/modifyreg$', views.modifyreg, name='modifyreg'),
    url(r'^(?P<id>[0-9]+)/detail$', views.detail, name='detail'),
    url(r'^(?P<id>[0-9]+)/searchid', views.searchid, name='searchid'),
    url(r'^findreg$', views.findreg, name='findreg'),
    url(r'^searchreg', views.searchreg, name='searchreg'),
    url(r'^(?P<id>[0-9]+)/get_testdata', views.get_testdata, name='get_testdata'),
    url(r'^(?P<id>[0-9]+)/save_testdata', views.save_testdata, name='save_testdata'),
]

Source/AutoCarWebApp/testreg/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


# Create your models here.
@python_2_unicode_compatible  # only if you need to support Python 2
class Applicant(models.Model):
    FirstName = models.CharField(max_length = 100)
    LastName = models.CharField(max_length = 100)
    Address = models.CharField(max_length = 300)
    SEX_TYPES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    )
    Sex = models.CharField(max_length = 1, choices=SEX_TYPES, default='M')
    DateOfBirth = models.DateField('birth date')
    Nationality = models.CharField(max_length = 100)
    ID_TYPES = (
        ('A', 'Aadhaar'),
        ('P', 'PAN'),
        ('O', 'Other')
    )
    IDType = models.CharField(max_length = 1, choices=ID_TYPES)
    UniqueID = models.CharField(max_length = 50)
    BiometricID = models.IntegerField(default = 0)
    def __str__(self):
        return self.FirstName

def user_directory_path(instance, filename):
    applicant = instance.applicant
    user = applicant.FirstName + "_" + applicant.LastName + "_" + str(applicant.id)
    return 'data/{0}/{1}/{2}'.format(user, instance.id, filename)
    
class Test(models.Model):
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    TestDate = models.DateTimeField('Test date')
    RESULT_TYPES = (
        ('P', 'PASS'),
        ('F', 'FAIL'),
        ('C', 'CANCELLED')
    )
    TestResult = models.CharField(max_length = 1, choices=RESULT_TYPES)
    TestData = models.FileField(upload_to=user_directory_path)
    

Source/AutoCarWebApp/testreg/forms.py
# -*- coding: utf-8 -*-
from django import forms

class TestDataForm(forms.Form):
    TestData = forms.FileField(
        label='Select a file',
        help_text='max. 2 megabytes'
    )

Source/AutoCarWebApp/testreg/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django import forms
from django.db import models
from django.template import RequestContext
from datetime import datetime
from testreg.models import Applicant
from testreg.models import Test
from testreg.forms import TestDataForm

# Create your views here.
from django.http import HttpResponse
from pip._vendor import requests

def index(request):
	return render(request, 'testreg/welcome.html')

def newreg(request):
	return render(request, 'testreg/new_registration.html')

def newapl(request):
	fname = request.POST['first_name']
	lname = request.POST['last_name']
	addr = request.POST['address']
	sex = request.POST['sex']
	bdate = request.POST['bdate']
	nationality = request.POST['nation']
	idtype = request.POST['idtype']
	id = request.POST['uid']
	new_applicant = Applicant(FirstName=fname, LastName=lname, Address=addr, Sex=sex, Nationality=nationality, IDType=idtype, UniqueID=id, DateOfBirth=bdate)
	new_applicant.save()
	new_applicant.BiometricID = new_applicant.id + 12345678;
	new_applicant.save()
	return HttpResponseRedirect(reverse('testreg:detail', args=(new_applicant.id,)))

def listreg(request):
	all_applicants = Applicant.objects.all()
	context = {'all_applicants': all_applicants}
	return render(request, 'testreg/list_applicants.html', context)

def findreg(request):
	return render(request, 'testreg/find_applicant.html')

def detail(request, id):
	applicant = get_object_or_404(Applicant, id=id)
	context = {'applicant': applicant}
	return render(request, 'testreg/applicant_details.html', context)

def deletereg(request, id):
	applicant = get_object_or_404(Applicant, id=id)
	applicant.delete()
	return HttpResponseRedirect(reverse('testreg:index'))

def updatereg(request, id):
	applicant = get_object_or_404(Applicant, id=id)
	context = {'applicant': applicant}
	return render(request, 'testreg/modify_details.html', context)
	
def modifyreg(request, id):
	applicant = get_object_or_404(Applicant, id=id)
	applicant.FirstName = request.POST['first_name']
	applicant.LastName = request.POST['last_name']
	applicant.Address = request.POST['address']
	Applicant.Sex = request.POST['sex']
	Applicant.DateOfBirth = request.POST['bdate']
	Applicant.Nationality = request.POST['nation']
	Applicant.IDType = request.POST['idtype']
	Applicant.UniqueID = request.POST['uid']
	applicant.save()
	return HttpResponseRedirect(reverse('testreg:detail', args=(id,)))

def searchid(request, id):
	try:
		applicant = Applicant.objects.get(BiometricID=id)
		context = {'applicant': applicant}
		return render(request, 'testreg/applicant_details.html', context)
	except Applicant.DoesNotExist:
		return render(request, 'testreg/applicant_details.html')

def searchreg(request):
	fname = request.POST['first_name']
	lname = request.POST['last_name']
	bdate = request.POST['bdate']
	uid = request.POST['uid']
	applicants = Applicant.objects.filter(FirstName__startswith=fname).filter(LastName__startswith=lname).filter(UniqueID__startswith=uid)
	context = {'all_applicants': applicants}
	return render(request, 'testreg/list_applicants.html', context)

def get_testdata(request, id):
	applicant = get_object_or_404(Applicant, id=id)
	documents = Test.objects.all()
	
	form = TestDataForm
	# Render list page with the documents and the form
	return render_to_response(
		'testreg/get_testdata.html',
		{'documents': documents, 'form': form, 'applicant': applicant},
		context_instance=RequestContext(request)
	)	
	
def save_testdata(request, id):
	applicant = get_object_or_404(Applicant, id=id)
	context = {'applicant': applicant}
	
	if request.method == 'POST':
		form = TestDataForm(request.POST, request.FILES)
		if form.is_valid():
			test = Test(TestData = request.FILES['TestData'])
			test.TestDate = datetime.now()
			test.TestResult = 'P'
			test.applicant = applicant
			test.save()
			return HttpResponseRedirect(reverse('testreg:detail', args=(id,)))
		else:
			return HttpResponseRedirect(reverse('testreg:index'))
	else:
		return render(request, 'testreg/get_testdata.html', context)
		
	

Source/AutoCarWebApp/testreg/templates/old/index.html
<h1 style="text-align: center;"><span style="color: #993366;"><strong>Welcome to RTO Driving Test</strong></span></h1>
<p>&nbsp;</p>
<p>&nbsp;</p>

<form action="{% url 'testreg:newreg' %}" method="POST">   
{% csrf_token %} 
    <input type=submit value="New Applicant"> <label> Click here for new registration </label>
    <p>&nbsp;</p> 
</form>    

<form action="{% url 'testreg:listreg' %}" method="POST">   
{% csrf_token %} 
    <input type=submit value="List Applicants"> <label> Click here for viewing existing registrations </label>
    <p>&nbsp;</p> 
</form>  

<form action="{% url 'testreg:findreg' %}" method="POST">   
{% csrf_token %} 
    <input type=submit value="Find Result">  <label> Click here for finding the result </label>
    <p>&nbsp;</p>
</form>

Source/AutoCarWebApp/testreg/templates/old/listreg.html
{% if all_applicants %}
    <th><td>FirstName</td>    <td>Last Name</td>  <td>BirthDate</td> <td>ID</td> </th>
    <ul>
    {% for applicant in all_applicants %}
        <li><tr><td>{{ applicant.FirstName }}</td> <td>{{ applicant.LastName }}</td> <td> {{ applicant.DateOfBirth }} </td> <td> {{ applicant.UniqueID }}</td> </tr></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No applicants are registered.</p>
{% endif %}

Source/AutoCarWebApp/testreg/templates/old/newreg.html
<form action="{% url 'testreg:newapl' %}" method="POST">
{% csrf_token %}
    <h1 style="text-align: left;">Enter the applicant details</h1>
    <p>&nbsp;</p>
    <label for="first_name">First Name: </label>
    <input id="first_name" type="text" name="first_name">
    <p>&nbsp;</p>
    
    <label for="last_name">Last Name: </label>
    <input id="last_name" type="text" name="last_name">
    <p>&nbsp;</p>
    
    <label for="address">Address: </label>
    <input id="address" type="text" name="address" cols="40"  rows="5"  style="width:200px; height:50px;">
    <p>&nbsp;</p>
    
    <label for="sex">Sex:     </label>
    <select id="sex" name="sex">
        <option value="Male">Male</option>
        <option value="Female">Female</option>
    </select>
    <p>&nbsp;</p>

    <label> Date of Birth: </label>
    <input type="date" id="bdate" name="bdate">
    <p>&nbsp;</p>
    
    <label for="idtype">Type of ID: </label>
    <select id="idtype" name="idtype">
        <option value="Aadhaar">Aadhaar</option>
        <option value="PAN">PAN</option>
    </select>
    <p>&nbsp;</p>
    
    <label for="id">ID: </label>
    <input id="id" type="text" name="id">
    <p>&nbsp;</p>

    <label for="nation">Nationality: </label>
    <input type="text" id="nation" name="nation" list="nationality" />
    <datalist id="nationality">
        <option>India</option>
        <option>British</option>
        <option>US</option>
        <option>French</option>
    </datalist>
    <p>&nbsp;</p>           
    
    <input type="submit" value="Register">
    <input type="submit" value="Cancel">
    <p>&nbsp;</p>

</form>

Source/AutoCarWebApp/testreg/templates/testreg/applicant_details.html
{% load staticfiles %}
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'testreg/style.css' %}" >
    <table width="450px">
    {% if applicant %}
        <h2> 
            <form align="center"> 
                <font  face="Calibri" color="white">Applicant Details </font> 
            </form>
        </h2>
        <tr>
        <td>
            <font  face="Calibri" color="white" for="first_name">First Name:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" name="first_name"> {{ applicant.FirstName }}</font>
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="last_name">Last Name:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" name="last_name"> {{ applicant.LastName }}</font>
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="address">Address:</font>
        </td>
        <td>
            <textarea readonly rows="6" cols="32" id="address" name="address"> {{ applicant.Address }} </textarea>
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="sex">Gender:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" name="sex"> {{ applicant.Sex }}</font>
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="bdate">Birth Date:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" name="bdate"> {{ applicant.DateOfBirth|date:"M d, Y"  }}</font>
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="idtype">Proof of Address:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" name="idtype"> {{ applicant.IDType  }}</font>
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="id">ID:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" name="id"> {{ applicant.UniqueID  }}</font>
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="nation">Nationality:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" name="nation"> {{ applicant.Nationality  }}</font> 
        </td>
        </tr>   
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="bid">Biometric ID:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" name="bid"> {{ applicant.BiometricID  }}</font>
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="bid">Test Results:</font>
        </td>
        {% for test in applicant.test_set.all %}
        <tr>
            <td/>
            <td>    
                <font  face="Calibri" color="white" for="bid"> {{ test.TestResult }}    ({{ test.TestDate|date:"M d, Y" }})</font>
            </td>
        </tr>
        {% endfor %}
                
        <tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/>

        <tr>
            <td>
                <form method="get" action="{% url 'testreg:updatereg' applicant.id %}">
                    <button type="submit">Modify</button>
                </form>
            </td>
            <td>
                <form method="get" action="{% url 'testreg:deletereg' applicant.id %}">
                    <button type="submit">Delete</button>
                </form>
            </td>
            <td>
                <form method="get" action="{% url 'testreg:get_testdata' applicant.id %}">
                    <button type="submit">Submit Test Data</button>
                </form>
            </td>
        </tr>
    {% else %}
        <p>No The specified applicant isn't registered.</p>
    {% endif %}        
        <tr>
            <td> </td>
            <td>
                <form method="get" action="{% url 'testreg:index' %}">
                    <button type="submit">Home</button>
                </form>
            </td>
        </tr>
    </table> 

 </link>

Source/AutoCarWebApp/testreg/templates/testreg/find_applicant.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'testreg/style.css' %}" >
    <head>
        <title>  Fine the candidate information</form></title>
    </head>
    <h2> 
        <form align="center"> 
        <font  face="Calibri" color="white">Applicant search </font> 
        </form>
    </h2>
    

    <form action="{% url 'testreg:searchreg' %}" method="POST">
    {% csrf_token %}    
    <table width="450px">
        <tr>
        <td>
            <font  face="Calibri" color="white" for="first_name">First Name:</font>
        </td>
        <td>
            <input type="text" id="first_name" name="first_name" maxlength="50" size="30">
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="last_name">Last Name:</font>
        </td>
        <td>
            <input type="text" id="last_name" name="last_name" maxlength="50" size="30">
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="bdate">Birth Date:</font>
        </td>
        <td>
            <input type="date" id="bdate" name="bdate">
        </td>
        </tr>
       
        <tr>
        <td>
            <font  face="Calibri" color="white" for="uid">ID:</font>
        </td>
        <td>
            <input type="text" id="uid" name="uid" maxlength="50" size="30">
        </td>
        </tr>
          
        <tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/>
        <tr>
        <td/>
        <td>
            <font  face="Calibri">
                <input type="submit" value="Search">
            </font>
        </td>       
    </form>
        <td>
            <form method="get" action="{% url 'testreg:index' %}">
                <button type="submit">Back</button>
            </form>
        </td>
        </tr>         
    </table>       
 </link>

Source/AutoCarWebApp/testreg/templates/testreg/get_testdata.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'testreg/style.css' %}" >
    <head>
        <title> Upload Test Data</form></title>
    </head>
    <h2> 
        <form align="center"> 
        <font  face="Calibri" color="white">Upload Test Data </font> 
        </form>
    </h2>

    <table width="450px">   
{% if applicant %}
    <form action="{% url 'testreg:save_testdata' applicant.id  %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.TestData.label_tag }} {{ form.TestData.help_text }}</p>
            <p>
                {{ form.TestData.errors }}
                {{ form.TestData }}
            </p>
            <p><input type="submit" value="Upload" /></p>
    {% else %}
        <p>No The specified applicant isn't registered.</p>
    {% endif %}             
        <tr>
            <td>
                <form method="get" action="{% url 'testreg:index' %}">
                    <button type="submit">Home</button>
                </form>
            </td>
        </tr>
    </table>            
 </link>

Source/AutoCarWebApp/testreg/templates/testreg/list_applicants.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'testreg/style.css' %}" >
    <table width="450px">
    {% if all_applicants %}
        <head>
            <title>  List all the applicants </form></title>
        </head>
        <h2> 
            <form align="center"> 
                <font  face="Calibri" color="white">List of Registered Applicants </font> 
            </form>
        </h2>

            <tr> 
                <td>
                    <font  face="Calibri" color="black" for="name"><b>Name</b></font>
                </td>
                <td>
                    <font  face="Calibri" color="black" for="dob"><b>Birth Date</b></font>
                </td>
                <td>
                    <font  face="Calibri" color="black" for="id"><b>ID</b></font>
                </td>
            </tr> 
        {% for applicant in all_applicants %}
            <tr>
                <td>
                    <a href="{% url 'testreg:detail' applicant.id %}"><font  face="Calibri" color="white" for="name">{{ applicant.FirstName }} {{ applicant.LastName }}</font></a>
                </td>
                <td>
                    <font  face="Calibri" color="white" for="dob">{{ applicant.DateOfBirth|date:"M d, Y" }}</font>
                </td>
                <td>
                    <font  face="Calibri" color="white" for="id">{{ applicant.UniqueID }}</font>
                </td>
            </tr>
        {% endfor %}
        <tr/><tr/><tr/>
    {% else %}
        <p>No applicants are registered.</p>
    {% endif %}
        <tr>
            <td>
                <form method="get" action="{% url 'testreg:index' %}">
                    <button type="submit">Back</button>
                </form>
            </td>
        </tr>
    </table>          
</link>

Source/AutoCarWebApp/testreg/templates/testreg/modify_details.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'testreg/style.css' %}" >
    <head><title>  Modify the candidate details</title></head>
    <h2> 
        <form align="center"> 
        <font  face="Calibri" color="white">Update Applicant Details </font> 
        </form>
    </h2>
    

{% if applicant %}
    <form action="{% url 'testreg:modifyreg' applicant.id %}" method="POST">
    {% csrf_token %}    
        <table width="450px">
        <tr>
        <td>
            <font  face="Calibri" color="white" for="first_name">First Name:</font>
        </td>
        <td>
            <input type="text" id="first_name" name="first_name" maxlength="50" size="30" value={{ applicant.FirstName }}>
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="last_name">Last Name:</font>
        </td>
        <td>
            <input type="text" id="last_name" name="last_name" maxlength="50" size="30" value={{ applicant.LastName }}>
        </td>
        </tr>
        <tr>
        <td>
            <font  face="Calibri" color="white" for="address">Address:</font>
        </td>
        <td>
            <textarea rows="6" cols="32" id="address" name="address">{{ applicant.Address }}</textarea>
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="sex">Gender:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" for="sex">
                <input type="radio" id="sex" name="sex" value="male">Male</input>
                <input type="radio" id="sex" name="sex" value="female">Female</input>
            </font>
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="bdate">Birth Date:</font>
        </td>
        <td>
            <input type="date" id="bdate" name="bdate" value={{ applicant.DateOfBirth }}>
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="idtype">Proof of Address:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" for="idtype">
            <input type="radio" id="idtype" name="idtype" value="aadhar">Aadhar</input>
            <input type="radio" id="idtype" name="idtype" value="pan">PAN</input>
            </font>
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="uid">ID:</font>
        </td>
        <td>
            <input type="text" id="uid" name="uid" maxlength="50" size="30" value={{ applicant.UniqueID }}>
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="nation">Nationality:</font>
        </td>
        <td>
        <font  face="Calibri">
            <input type="text" id="nation" name="nation" list="nationality" value={{ applicant.Nationality }}>
            <datalist id="nationality">
                <option>India</option>
                <option>British</option>
                <option>US</option>
                <option>French</option>
            </datalist>
        </font> 
        </td>
        </tr>
    
        <tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/>
        <tr>
        <td><td><td>
        <td>
            <font  face="Calibri">
                <input type="submit" value="Update">
            </font>
        </td>
        </td></td></td>
        <td><button type="cancel" onclick="welcome.html">Cancel</button></td>
        </tr>        
    </form> 
{% else %}
        <p>No The specified applicant isn't registered.</p>
{% endif %}             
 </link>

Source/AutoCarWebApp/testreg/templates/testreg/new_registration.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'testreg/style.css' %}" >
    <head>
        <title>  Register a candidate </form></title>
    </head>
    <h2> 
        <form align="center"> 
        <font  face="Calibri" color="white">Candidate Registration </font> 
        </form>
    </h2>
    

    {% if applicant %}
    {% endif %}
    <form action="{% url 'testreg:newapl' %}" method="POST">
    {% csrf_token %}    
        <table width="450px">
        <tr>
        <td>
            <font  face="Calibri" color="white" for="first_name">First Name:</font>
        </td>
        <td>
            <input type="text" id="first_name" name="first_name" maxlength="50" size="30">
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="last_name">Last Name:</font>
        </td>
        <td>
            <input type="text" id="last_name" name="last_name" maxlength="50" size="30">
        </td>
        </tr>
        <tr>
        <td>
            <font  face="Calibri" color="white" for="address">Address:</font>
        </td>
        <td>
            <textarea rows="6" cols="32" id="address" name="address"> </textarea>
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="sex">Gender:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" for="sex">
                <input type="radio" id="sex" name="sex" value="male">Male</input>
                <input type="radio" id="sex" name="sex" value="female">Female</input>
            </font>
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="bdate">Birth Date:</font>
        </td>
        <td>
            <input type="date" id="bdate" name="bdate">
        </td>
        </tr>

        <tr>
        <td>
            <font  face="Calibri" color="white" for="idtype">Proof of Address:</font>
        </td>
        <td>
            <font  face="Calibri" color="white" for="idtype">
            <input type="radio" id="idtype" name="idtype" value="aadhar">Aadhar</input>
            <input type="radio" id="idtype" name="idtype" value="pan">PAN</input>
            </font>
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="uid">ID:</font>
        </td>
        <td>
            <input type="text" id="uid" name="uid" maxlength="50" size="30">
        </td>
        </tr>
        
        <tr>
        <td>
            <font  face="Calibri" color="white" for="nation">Nationality:</font>
        </td>
        <td>
        <font  face="Calibri">
            <input type="text" id="nation" name="nation" list="nationality" />
            <datalist id="nationality">
                <option>India</option>
                <option>British</option>
                <option>US</option>
                <option>French</option>
            </datalist>
        </font> 
        </td>
        </tr>
    
        <tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/><tr/>
        <tr>
        <td><td><td>
        <td>
            <font  face="Calibri">
                <input type="submit" value="Register">
            </font>
        </td>
        </td></td></td>
        </tr>        
    </form>
            <form method="get" action="{% url 'testreg:index' %}">
                <button type="submit">Cancel</button>
            </form>
 </link>

Source/AutoCarWebApp/testreg/templates/testreg/welcome.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'testreg/style.css' %}" >
    <head>
        <title>Welcome</title>
    </head>
    <h1 style="text-align: center;"> 
        <font  face="Calibri" color="white">Welcome to computerized driving test </font>
    </h1>

    <font  face="Calibri" size=4 color="white" for="selectoption">Choose your option: </font>
    <table width="450px">
        <br>
        <tr>
        <br>
        <td>
            <font  face="Calibri" color="white" for="newapplicant">Click <a href="{% url 'testreg:newreg' %}">here </a> to add a New Applicant:</font>
        </td>
        </tr>
        <tr>
        
        <td>
        <br>
            <font  face="Calibri" color="white" for="newapplicant">Click <a href="{% url 'testreg:listreg' %}">here </a> to view list of Applicants:</font>
        </td>
        
        </tr>
        <tr>
        <td>
        <br>
            <font  face="Calibri" color="white" for="newapplicant">Click <a href="{% url 'testreg:findreg' %}">here </a> to view result of a Applicants</font>
        </td>
        </tr>
    </table>
</link>